### ISSUE TITLE
Install "interactive_table1.R", "label.R" and "reactable2.R"

### ISSUE THREAD

**Issue by zhangr100** [elong0527/metalite.table1#1]
It seems that R scripts like "interactive_table1.R", "label.R" and "reactable2.R" under R folder will not be installed automatically if using "install_github".

**Comment by elong0527** [comment]
You are right, they are internal functions. If you need to use them please call `metalite:::interactive_table1`.

reference: https://stackoverflow.com/questions/2675502/what-does-the-symbol-mean-in-r

**Comment by elong0527** [comment]
If you are referring error when you run code below. It will be fixed after the PR https://github.com/Merck/metalite/pull/82 merged. 

```
devtools::install_github("elong0527/metalite.table1")

library(metalite.table1)
meta <- metalite_table1(~ AGE + SEX + RACE + BMIBLGR1 | ARM, # formula for analysis variables and group 
                data = r2rtf::r2rtf_adsl,                    # source data
                id = "USUBJID")                              # unique subject id
```
