### ISSUE TITLE
Specify page size 

### ISSUE THREAD

**Issue by elong0527** [elong0527/metalite.table1#10]
refer #8

add an argument following reachable style from https://glin.github.io/reactable/reference/reactable.html

**Comment by czqiu** [comment]
which option should I use? thanks!

**Comment by elong0527** [comment]
You can find examples in https://glin.github.io/reactable/articles/examples.html#pagination

**Comment by elong0527** [comment]
In current development version, we allow user to specify additional arguments from `reactable`. So it can use the `defaultPageSize`. 

But it might not a good use case for this package with too many rows, because we can not keep the first 2 rows in each page. 

```
devtools::load_all()
metalite_table1(
  ~ RACE | ARM, 
  data = r2rtf::r2rtf_adsl, 
  id = "USUBJID", 
  defaultPageSize = 4
)
```

**Comment by czqiu** [comment]
how to install the development version? I could not find it in your introduction page. Thanks!

**Comment by czqiu** [comment]
can this option to be used: defaultColDef = list(style = list(fontSize = '10px')) to change font size? thanks
