### ISSUE TITLE
can we remove repeated row in loop of tables?

### ISSUE THREAD

**Issue by czqiu** [elong0527/metalite.table1#11]
Hi Yilong,

Another thing is that if we can remove repeated rows from the loop of tables? for example in your code and results:
![image](https://github.com/elong0527/metalite.table1/assets/8573359/32af8757-7714-4cfd-9978-1b289a26f559)

The underline red parts are repeated from table 1 and table 2 basically. It will be nice if there is an option to remove the second same thing from table 2. What do you think?

Thanks
Eric

**Comment by elong0527** [comment]
The row can be removed after setting FALSE in the line below. 

https://github.com/elong0527/metalite.table1/blob/main/R/metalite_table1.R#L56

However, I need to balance number of input arguments and flexibility of the tool. 

For an exploratory tool, It might be OK to keep some redundancy.

**Comment by elong0527** [comment]
In current development version, the feature is enabled by the `header` argument with examples below. 

```
devtools::load_all()
metalite_table1(
  ~ AGE + RACE | ARM, 
  data = r2rtf::r2rtf_adsl, 
  id = "USUBJID", 
  header = TRUE
)

metalite_table1(
  ~ AGE + RACE | ARM, 
  data = r2rtf::r2rtf_adsl, 
  id = "USUBJID", 
  header = FALSE
)

metalite_table1(
  ~ AGE + RACE | ARM, 
  data = r2rtf::r2rtf_adsl, 
  id = "USUBJID", 
  header = c(FALSE, TRUE)
)
```
