### ISSUE TITLE
how to install development version?

### ISSUE THREAD

**Issue by czqiu** [elong0527/metalite.table1#12]
how to install the development version? I could not find it in your introduction page. 
can this option to be used: defaultColDef = list(style = list(fontSize = '10px')) to change font size? thanks

**Comment by czqiu** [comment]
I find a way to change the font size now:

htmltools::tags$div(
  style = "font-size: 10px;", metalite_table1(~ prtrt|TRTGRPCD,
        data = surg.ped,
        id = "SUBJID"
      ))

In this way, I can have :

![image](https://github.com/elong0527/metalite.table1/assets/8573359/a0566d3c-85b6-403f-8bac-41f22ccaba35)

**Comment by elong0527** [comment]
Using 'devtools::install_github'

Refer https://www.rdocumentation.org/packages/devtools/versions/1.13.6/topics/install_github

Thanks for the suggestions to change font size using html tags.
