### ISSUE TITLE
font size adjustment and number of record to display like options in DT package?

### ISSUE THREAD

**Issue by czqiu** [elong0527/metalite.table1#8]
Hi Yilong,

Is there a way to adjust the font size? The table has fixed width in QUARTO markdown HTML output. So, it will be nice if it can have the option to specify column width or font size to make it smaller. Also, you can see the table looks pretty busy when I have multiple visits under the same question. 

![image](https://github.com/elong0527/metalite.table1/assets/8573359/7c0d4647-e71c-496f-87ee-4cad074f010d)

Will an option for two level table be better layout?
![image](https://github.com/elong0527/metalite.table1/assets/8573359/c7e1e88b-bf14-48ca-bc36-d61605031fa5)

Also, is there a way to limit the number of record to display when doing the frequency table? For date variable, I can only treat it as character. Then, it list 50 records in the first page in my QUARTO HTML output.

Thanks!

**Comment by elong0527** [comment]
- Specify column width: #9 
 - Multiple layout: the functionality is possible, but I did not have a clear idea how to design the input/output that fit into the package design.  
    + How about specify "RGI-C" only and provide the full name in the footnote? 
    + How about specify the information in the table title or section title. 
 - Specify page size for categorical table. #10

**Comment by czqiu** [comment]
Hi Yilong, Did you add new option for #9? I read the link. It goes to reactable. Are you talking that your package can work with reactable option together? 
Level 1 is the lab name, Level 2 is the timepoints at which lab has been measured. 
![image](https://github.com/elong0527/metalite.table1/assets/8573359/d2ef8fec-21ff-4e4b-94e1-7cff9a565250)
That is the layout I am talking. not the short name of RGI-C.

thanks
Eric

**Comment by elong0527** [comment]
Not yet, I just put my thoughts there for possible solution. 

The request is for a different table layout that may not be fully support in this package. 

Yet, the two specific feature described in #9 and #10 will be added when I find some time in the future.

**Comment by czqiu** [comment]
Thanks very much for all helps!

**Comment by elong0527** [comment]
Thanks for the feedbacks. 

All planned feature discussed in this issue have been closed. A new version will be released to CRAN. 

I will close this issue. 

Let's open new issues if there are additional suggestions.
